# =============================================================================
# dbt Profiles Configuration 
# =============================================================================
# ClickHouse adapter for 8GB RAM machines
# =============================================================================

lakehouse:
  target: clickhouse
  outputs:
    clickhouse:
      type: clickhouse
      driver: http
      host: clickhouse
      port: 8123
      user: default
      password: 'clickhouse123'
      schema: lakehouse
      threads: 2
      connect_timeout: 60
